Algoritmo "01"
//samoel weber

Var
maior,valor1,valor2: inteiro
nome_usuario: caracter

Inicio
escreva (" nome do usuario ")
leia (nome_usuario)
escreva (" digite o primeiro valor ")
leia (valor1)
escreva ("digite  o segundo valor ")
leia (valor2)
se (valor1>=valor2)entao
escreva( "maior numero digitado foi:",valor1)
senao
escreva("o maior numero digitado foi :",valor2)
 fimse


Fimalgoritmo