Algoritmo "leitor"

Var
altura1,altura2:real
nome1,nome2:caracter


Inicio

escreval(" escreva o nome da primeira pessoa ")
leia (nome1)
escreval (" qual o sua altura? ")
leia (altura1)
escreval (" escreva o nome da segunda pessoa ")
leia (nome2)
escreval (" qual a sua altura? ")
leia(altura2)
escreval(" primeiro nome informado ",nome1," com altura ",altura1," segundo nome informado ",nome2," com altura ",altura2)
Fimalgoritmo