Algoritmo "dor de cabeça"

Var
x:real
y:inteiro
a:caractere
l:logico


Inicio
x<-2.5
y<-6
a<-"teste"
l<-verdadeiro
escreval("x" , x:4:1, y+3:4)// escreve: x 2.5 9
escreval(a, " ok") //escreve: testeok (e depois pula linha)
escreval (a, " ok") //escreve: teste ok (e depois pula linha)
escreval (a +  " ok") //escreve: teste ok (e depois pula linha)
escreva (l) //escreve: verdadeiro


Fimalgoritmo